include "/etc/dhcp/ddns.key";

ddns-update-style interim;
ddns-domainname "serafin.test.";
ddns-rev-domainname "58.168.192.in-addr.arpa.";

default-lease-time 86400;
max-lease-time 691200;

option domain-name "serafin.test";
option domain-name-servers 192.168.58.10;

subnet 192.168.58.0 netmask 255.255.255.0 {
  range 192.168.58.100 192.168.58.200;
  option routers 192.168.58.1;
  option domain-name-servers 192.168.58.10;

  zone serafin.test. {
        primary 192.168.58.10;
        key "ddns-key";
  }

  zone 58.168.192.in-addr.arpa. {
        primary 192.168.58.10;
        key "ddns-key";
  }
}
